select STUDENT.* , STUDENT_GROUP.GROUP_NAME, ROLE.ROLE_NAME, TIME_TABLE.TIME_TABLE_NAME, WORK_DAY.DAY_NAME, LESSON.LESSON_NAME, LESSON_DAY.LESSON_PLACE, LESSON_DAY.LESSON_TIME from STUDENT
left join STUDENT_GROUP on STUDENT.GROUP_ID = STUDENT_GROUP.GROUP_ID
inner join ROLE on STUDENT.ROLE_ID = ROLE.ROLE_ID
left join TIME_TABLE on STUDENT_GROUP.GROUP_ID = TIME_TABLE.GROUP_ID
left join WORK_DAY on TIME_TABLE.TIME_TABLE_ID = WORK_DAY.TIME_TABLE_ID
left join LESSON_DAY on WORK_DAY.DAY_ID = LESSON_DAY.DAY_ID
left join LESSON on LESSON_DAY.LESSON_ID = LESSON.LESSON_ID
;