DROP SCHEMA IF EXISTS TIMETABLE;
CREATE SCHEMA TIMETABLE;

DROP TABLE IF EXISTS TIMETABLE.ROLE;
DROP TABLE IF EXISTS TIMETABLE.STUDENT_GROUP;
DROP TABLE IF EXISTS TIMETABLE.STUDENT;
DROP TABLE IF EXISTS TIMETABLE.TIME_TABLE;
DROP TABLE IF EXISTS TIMETABLE.WORK_DAY;
DROP TABLE IF EXISTS TIMETABLE.LESSON;
DROP TABLE IF EXISTS TIMETABLE.LESSON_DAY;

CREATE TABLE TIMETABLE.ROLE (
  ROLE_ID           VARCHAR(100)    NOT NULL,
  ROLE_NAME         VARCHAR(10)     NOT NULL,

  PRIMARY KEY(ROLE_ID)
);

CREATE TABLE TIMETABLE.STUDENT_GROUP (
  GROUP_ID          VARCHAR(100)    NOT NULL,
  GROUP_NAME        VARCHAR(10)    NOT NULL,

  PRIMARY KEY(GROUP_ID)
);

CREATE TABLE TIMETABLE.STUDENT (
  STUDENT_ID        VARCHAR(100)    NOT NULL,
  STUDENT_NAME      VARCHAR(100)    NOT NULL,
  STUDENT_SURNAME   VARCHAR(100)    NOT NULL,
  STUDENT_LOGIN     VARCHAR(100)    NOT NULL,
  STUDENT_PASSWORD  VARCHAR(100),
  GROUP_ID          VARCHAR(100),
  ROLE_ID           VARCHAR(100)    NOT NULL,

  PRIMARY KEY(STUDENT_ID),
  FOREIGN KEY(ROLE_ID) REFERENCES TIMETABLE.ROLE(ROLE_ID),
  FOREIGN KEY(GROUP_ID) REFERENCES TIMETABLE.STUDENT_GROUP(GROUP_ID)
);


CREATE TABLE TIMETABLE.TIME_TABLE (
  TIME_TABLE_ID     VARCHAR(100)    NOT NULL,
  TIME_TABLE_NAME   VARCHAR(5)      NOT NULL,
  GROUP_ID          VARCHAR(100)    NOT NULL,

  PRIMARY KEY(TIME_TABLE_ID),
  FOREIGN KEY(GROUP_ID) REFERENCES TIMETABLE.STUDENT_GROUP(GROUP_ID) ON DELETE CASCADE
);

CREATE TABLE TIMETABLE.WORK_DAY (
  DAY_ID            VARCHAR(100)    NOT NULL,
  DAY_NAME          VARCHAR(10)     NOT NULL,
  TIME_TABLE_ID     VARCHAR(100)    NOT NULL,

  PRIMARY KEY(DAY_ID),
  FOREIGN KEY(TIME_TABLE_ID) REFERENCES TIMETABLE.TIME_TABLE(TIME_TABLE_ID) ON DELETE CASCADE
);

CREATE TABLE TIMETABLE.LESSON (
  LESSON_ID         VARCHAR(100)    NOT NULL,
  LESSON_NAME       VARCHAR(10)     NOT NULL,


  PRIMARY KEY(LESSON_ID)
);


CREATE TABLE TIMETABLE.LESSON_DAY (
  DAY_ID            VARCHAR(100)    NOT NULL,
  LESSON_ID         VARCHAR(100)    NOT NULL,
  LESSON_PLACE      VARCHAR(10)     NOT NULL,
  LESSON_TIME       VARCHAR(15)     NOT NULL,

  FOREIGN KEY(DAY_ID) REFERENCES TIMETABLE.WORK_DAY(DAY_ID) ON DELETE CASCADE,
  FOREIGN KEY(LESSON_ID) REFERENCES TIMETABLE.LESSON(LESSON_ID) ON DELETE CASCADE
);